package com.vylo.common.util

const val WEB_URL = "web_url"
const val RESPONSES_COUNT = "responses_count"
const val WEB_DATA = "web_data"
const val VIDEO_DATA = "video_data"

const val VIDEO_TYPE = "video_type"

const val FOLLOWING_TYPE = "following_type"
const val FOLLOWING_BACK_TYPE = "following_back_type"
const val IS_MY_PROFILE = "is_my_profile"
const val FOLLOW_TYPE = "follow_type"
const val FOLLOW_USER_DATA = "follow_user_data"
const val OPEN_WEB_FROM = "open_web_from"

const val CATEGORY_NAME_RESULT = "category_name_result"
const val CATEGORY_NAME = "category_name"
const val PROFILE_INFO = "profile_info"
const val PROFILE_INFO_SETTINGS_MY_ACCOUNT = "profile_info_settings_account"
const val PARENT_FRAGMENT = "parent_fragment"
const val USER_PROFILE = "user_profile"
const val UPLOAD_INFO = "upload_info"
const val RESPOND_INFO = "respond_info"
const val RESPONSES_INFO = "responses_info"
const val TERMS = "https://vylo.com/terms"
const val PRIVACY = "https://vylo.com/privacy "
const val GRAPH_ID = "graph_id"
const val RESPONSE_TYPE = "response_type"
const val DESTINATION_OF_NAVIGATION_FRAGMENT = "destination_nav_fragment"
const val TITLE_OF_SHEET = "TITLE"
const val FOLLOWING_IDS = "following_ids"
const val DEEP_LINK_ID = "deep_link"
const val CATEGORY_ID = "category_id"
const val VIDEO_NOT_ALIVE = "video_not_alive"
const val PROFILE_TYPE = "profile_type"
